db:
  train_db_path: ./src/dataset/test.lmdb
  valid_db_path: ./src/dataset/test.lmdb
  test_db_path: ./src/dataset/test.lmdb

data:
  min_mz: 140.0
  max_mz: 2500.0
  min_intensity: 0.01
  remove_precursor_tol: 2.0
  n_peaks: 150

model:
  d_model: 512
  d_ff: 2048
  n_heads: 8 
  dropout: 0.1
  input_dim: 2
  output_dim: 27
  num_layers: 6

train:
  batch_size: 4
  num_workers: 0
  num_epochs: 100
  lr: 1e-4